### ISSUE TITLE
Add options for custom color scheme

### ISSUE THREAD

**Issue by aguirre-matteo** [aguirre-matteo/mtp-tui#3]
Implement options for setting custom colors for the background, the title and the selected item on the list. Those settings should be configured under the `colors` section, like this:
```yaml
colors:
  title: #76b5c5
  background: #000000
  selected: #32bd82
```
