### ISSUE TITLE
Opening a Device's storage with prefered File Manager

### ISSUE THREAD

**Issue by aguirre-matteo** [aguirre-matteo/mtp-tui#7]
There should be a keybind for opening the Device's storage using a specified File Manager (like Dolphin, Yazi, etc). Which File Manager to use will be set using the `file-manager` option:

```yaml
# ...
file-manager: yazi
mount:
  point: /home/<user>/mtp
  options: default_permissions,allow_other
```
